### ISSUE TITLE
Can't find handler for document

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [mathjax/mathjax-v3#265]
I'm pretty new to MathJax, but I do need to implement it through Webpack (actually through  Symfony/Encore).

This is the error I get when running my code:
![image](https://user-images.githubusercontent.com/293596/58424948-fcf23380-806e-11e9-9218-3c0fcbc760fb.png)

My app.js: //That is wrapped by webpack
```
global.MathJax = require("mathjax3").MathJax;
global.MathJax_TeX = require("mathjax3/mathjax3/input/tex").TeX;
global.MathJax_AllPackages = require('mathjax3/mathjax3/input/tex/AllPackages').AllPackages;
global.MathJax_SVG = require("mathjax3/mathjax3/output/svg").SVG;
```

My twig/html:
```
const tmpObj = MathJax.document(document, {               //THIS IS LINE 257 from 39
     InputJax: new MathJax_TeX({
         packages: MathJax_AllPackages
     }),
     OutputJax: new MathJax_SVG({}, {
         useGlobalCache: false,
         scale: 100,
         blacker: 30
     })
});
```

I've also tried to use window.document, based on a suggestion from a different issue here, IE related.

Any ideas why this is happening and what can I do to solve it?

**Comment by dpvc** [comment]
The problem is that you haven't registered a document handler, as the message indicates.  You need to do something like:

```
const liteAdaptor = require('mathjax3/mathjax3/adaptors/liteAdaptor.js').liteAdaptor;
const RegisterHTMLHandler = require('mathjax3/mathjax3/handlers/html.js').RegisterHTMLHandler;
RegisterHTMLHandler(liteAdaptor());
```

before the `MathJax.document()` call.  This allows MathJax to work with HTML documents (as opposed to other types, like Markdown, for instance, though currently HTML is the only available format).  See the [node demos](https://github.com/mathjax/mj3-demos-node/tree/master/direct) for examples.  There are also examples using the MathJax components rather than direct calls; see the [top level](https://github.com/mathjax/mj3-demos-node/) directory for details.

You should also note that your creation of the SVG output jax is not being configured properly.  The options should be the *first* argument, not the second.  You may have tried that and gotten error messages, since some of the option names have changed since version 2.  In particular, `useGlobalCache: false` is now either `fontCache: 'local'` or `fontCache: 'none'` depending on what you want (`'local'` is the default), and `blacker` is no longer available.  Finally, the `scale` value is now a multiplying factor, not a percentage, so `scale: 100` would become `scale: 1` (which is the default).  So it looks like you could drop the options for SVG entirely, as all the values are the defaults.

**Comment by flaushi** [comment]
Hey great thread, but still I don't really get it, I'd be grateful for your help.
My webpack'd `mathjax.js`:
```
global.MathJax = require("mathjax3").MathJax;
global.MathJax_TeX = require("mathjax3/mathjax3/input/tex").TeX;
global.MathJax_AllPackages = require('mathjax3/mathjax3/input/tex/AllPackages').AllPackages;
global.MathJax_SVG = require("mathjax3/mathjax3/output/svg").SVG;
$(document).ready(function () {
    const liteAdaptor = require('mathjax3/mathjax3/adaptors/liteAdaptor.js').liteAdaptor;
    const RegisterHTMLHandler = require('mathjax3/mathjax3/handlers/html.js').RegisterHTMLHandler;
    RegisterHTMLHandler(liteAdaptor());
    const tmpObj = MathJax.document(document, {               //THIS IS LINE 257 from 39
        InputJax: new MathJax_TeX({
            packages: MathJax_AllPackages
        }),
        OutputJax: new MathJax_SVG({})
    });
});
```
My twig code is quite simple:
```
{% block body %}
$$ x^^ = \sqrt{4}{x}$$
{% endblock%}
{% block javascripts %}
	{{ parent() }}
   	{{ encore_entry_script_tags('mathjax') }}
{% endblock%}
```
I also see error `Uncaught Error: Can't find handler for document`.

**Comment by flaushi** [comment]
Hey I found a solution now, and want to share it here, in case somebody encounters the same problem.
```
global.MathJax = require("mathjax3").MathJax;
global.MathJax_TeX = require("mathjax3/mathjax3/input/tex").TeX;
global.MathJax_AllPackages = require('mathjax3/mathjax3/input/tex/AllPackages').AllPackages;
global.MathJax_SVG = require("mathjax3/mathjax3/output/svg").SVG;
const adaptor = require("mathjax3/mathjax3/adaptors/browserAdaptor").browserAdaptor();
require("mathjax3/mathjax3/handlers/html.js").RegisterHTMLHandler(adaptor);

$(document).ready(function () {

    const tmpObj = MathJax.document(document, {
        InputJax: new MathJax_TeX({
            packages: MathJax_AllPackages
        }),
        OutputJax: new MathJax_SVG({
            scale: 150
        })
    });
    tmpObj.findMath()
        .compile()
        .getMetrics()
        .typeset()
        .updateDocument();
});
```
in my twig:
```
{% block body %}
$$ x^{\frac{1}{4}} = \sqrt[4]{x}$$
{% endblock%}
{% block javascripts %}
	{{ parent() }}
   	{{ encore_entry_script_tags('mathjax') }}
```
I am using encore (webpack) in my symfony 4 application. Note that the `parent()` script call gives me `jQuery`...

**Comment by Aleyasen** [comment]
@dpvc I followed your instruction but still got an error in node:
This is my code:
```
const mathjax = require('mathjax-full/js/mathjax.js').mathjax;
const TeX = require('mathjax-full/js/input/tex.js').TeX;
const SVG = require('mathjax-full/js/output/svg.js').SVG;
const liteAdaptor = require('mathjax-full/js/adaptors/liteAdaptor.js').liteAdaptor;
const RegisterHTMLHandler = require('mathjax-full/js/handlers/html.js').RegisterHTMLHandler;
const AllPackages = require('mathjax-full/js/input/tex/AllPackages.js').AllPackages;

//
//  Read the HTML file
//
const htmlfile = require('fs').
    readFileSync("/path/to/file.html", 'utf8');

//
//  Create DOM adaptor and register it for HTML documents
//
const adaptor = liteAdaptor({fontSize: 16});
RegisterHTMLHandler(adaptor);

//
//  Create input and output jax and a document using them on the content from the HTML file
//
const tex = new TeX({packages: AllPackages.sort().join(', ').split(/\s*,\s*/)});
const svg = new SVG({fontCache: 'global', exFactor: 8 / 16});
const html = mathjax.document(htmlfile, {InputJax: tex, OutputJax: svg});

//
//  Typeset the document
//
html.render();

//
//  Output the resulting HTML
//
console.log(adaptor.outerHTML(adaptor.root(html.document)));
```

and I got this error:
```
/usr/local/bin/node /project/bin/www
/project/node_modules/mathjax-full/js/core/HandlerList.js:56
        throw new Error("Can't find handler for document");
        ^

Error: Can't find handler for document
    at HandlerList.handlesDocument (/project/node_modules/mathjax-full/js/core/HandlerList.js:56:15)
    at HandlerList.document (/project/node_modules/mathjax-full/js/core/HandlerList.js:60:21)
    at Object.document (/project/node_modules/mathjax-full/js/mathjax.js:9:41)
    at Object.<anonymous> (/project/../mathJax.js:25:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/somepath/somefile.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)

Process finished with exit code 1
```

Did I miss something?

**Comment by dpvc** [comment]
@Aleyasen, your code works for me (when I change the `/path/to/file.html` to point to an actual one).  Perhaps it has to do with the content of your html file?  Can you pass along a sample of the HTML file itself?  If you pass a string as the document, as you do in this case, it does have to parse as an HTML document using the given adaptor.  The LiteDOM adaptor is not all that sophisticated, so it is possible that the HTML in your file confuses it.

**Comment by Aleyasen** [comment]
Thanks @dpvc for the quick reply, I used a simpler html file and the SVG was generated without the `Can't find handler for document` error. However, when I opened the generated SVG (that wrapped in a html document) in browser I cannot see any formula. This is the generated html. Do you have any thoughts about the possible reasons?

```
<html><head><style id="MJX-SVG-styles">
mjx-container[jax="SVG"] > svg {
  overflow: visible;
}

mjx-container[jax="SVG"] > svg a {
  fill: blue;
  stroke: blue;
}

mjx-container[jax="SVG"][display="true"] {
  display: block;
  text-align: center;
  margin: 1em 0;
}

mjx-container[jax="SVG"][justify="left"] {
  text-align: left;
}

mjx-container[jax="SVG"][justify="right"] {
  text-align: right;
}

g[data-mml-node="merror"] > g {
  fill: red;
  stroke: red;
}

g[data-mml-node="merror"] > rect[data-background] {
  fill: yellow;
  stroke: none;
}

g[data-mml-node="mtable"] > line[data-line] {
  stroke-width: 70px;
  fill: none;
}

g[data-mml-node="mtable"] > rect[data-frame] {
  stroke-width: 70px;
  fill: none;
}

g[data-mml-node="mtable"] > .mjx-dashed {
  stroke-dasharray: 140;
}

g[data-mml-node="mtable"] > .mjx-dotted {
  stroke-linecap: round;
  stroke-dasharray: 0,140;
}

g[data-mml-node="mtable"] > svg {
  overflow: visible;
}

[jax="SVG"] mjx-tool {
  display: inline-block;
  position: relative;
  width: 0;
  height: 0;
}

[jax="SVG"] mjx-tool > mjx-tip {
  position: absolute;
  top: 0;
  left: 0;
}

mjx-tool > mjx-tip {
  display: inline-block;
  padding: .2em;
  border: 1px solid #888;
  font-size: 70%;
  background-color: #F8F8F8;
  color: black;
  box-shadow: 2px 2px 5px #AAAAAA;
}

g[data-mml-node="maction"][data-toggle] {
  cursor: pointer;
}

mjx-status {
  display: block;
  position: fixed;
  left: 1em;
  bottom: 1em;
  min-width: 25%;
  padding: .2em .4em;
  border: 1px solid #888;
  font-size: 90%;
  background-color: #F8F8F8;
  color: black;
}

.MathJax path {
  stroke-width: 3;
}
</style></head><body><h1>Title</h1>

<div>
  When $a \ne 0$, there are two solutions to <mjx-container class="MathJax" jax="SVG"><svg style="vertical-align: -0.186ex" xmlns="http://www.w3.org/2000/svg" width="16.328ex" height="2.072ex" role="img" focusable="false" viewBox="0 -833.9 7217 915.9" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)"><g data-mml-node="math"><g data-mml-node="mi"><use xlink:xlink:href="#MJX-TEX-I-61"></use></g><g data-mml-node="msup" transform="translate(529, 0)"><g data-mml-node="mi"><use xlink:xlink:href="#MJX-TEX-I-78"></use></g><g data-mml-node="mn" transform="translate(572, 363) scale(0.707)"><use xlink:xlink:href="#MJX-TEX-N-32"></use></g></g><g data-mml-node="mo" transform="translate(1726.8, 0)"><use xlink:xlink:href="#MJX-TEX-N-2B"></use></g><g data-mml-node="mi" transform="translate(2727, 0)"><use xlink:xlink:href="#MJX-TEX-I-62"></use></g><g data-mml-node="mi" transform="translate(3156, 0)"><use xlink:xlink:href="#MJX-TEX-I-78"></use></g><g data-mml-node="mo" transform="translate(3950.2, 0)"><use xlink:xlink:href="#MJX-TEX-N-2B"></use></g><g data-mml-node="mi" transform="translate(4950.4, 0)"><use xlink:xlink:href="#MJX-TEX-I-63"></use></g><g data-mml-node="mo" transform="translate(5661.2, 0)"><use xlink:xlink:href="#MJX-TEX-N-3D"></use></g><g data-mml-node="mn" transform="translate(6717, 0)"><use xlink:xlink:href="#MJX-TEX-N-30"></use></g></g></g></svg></mjx-container> and they are
  <mjx-container class="MathJax" jax="SVG" display="true"><svg style="vertical-align: -1.575ex" xmlns="http://www.w3.org/2000/svg" width="21.652ex" height="5.499ex" role="img" focusable="false" viewBox="0 -1734.5 9570 2430.5" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)"><g data-mml-node="math"><g data-mml-node="mi"><use xlink:xlink:href="#MJX-TEX-I-78"></use></g><g data-mml-node="mo" transform="translate(849.8, 0)"><use xlink:xlink:href="#MJX-TEX-N-3D"></use></g><g data-mml-node="TeXAtom" transform="translate(1905.6, 0)"><g data-mml-node="mfrac"><g data-mml-node="mrow" transform="translate(220, 676)"><g data-mml-node="mo"><use xlink:xlink:href="#MJX-TEX-N-2212"></use></g><g data-mml-node="mi" transform="translate(778, 0)"><use xlink:xlink:href="#MJX-TEX-I-62"></use></g><g data-mml-node="mo" transform="translate(1429.2, 0)"><use xlink:xlink:href="#MJX-TEX-N-B1"></use></g><g data-mml-node="msqrt" transform="translate(2429.4, 0)"><g transform="translate(1000, 0)"><g data-mml-node="msup"><g data-mml-node="mi"><use xlink:xlink:href="#MJX-TEX-I-62"></use></g><g data-mml-node="mn" transform="translate(429, 363) scale(0.707)"><use xlink:xlink:href="#MJX-TEX-N-32"></use></g></g><g data-mml-node="mo" transform="translate(1054.8, 0)"><use xlink:xlink:href="#MJX-TEX-N-2212"></use></g><g data-mml-node="mn" transform="translate(2055, 0)"><use xlink:xlink:href="#MJX-TEX-N-34"></use></g><g data-mml-node="mi" transform="translate(2555, 0)"><use xlink:xlink:href="#MJX-TEX-I-61"></use></g><g data-mml-node="mi" transform="translate(3084, 0)"><use xlink:xlink:href="#MJX-TEX-I-63"></use></g></g><g data-mml-node="mo" transform="translate(0, 148.5)"><use xlink:xlink:href="#MJX-TEX-SO-221A"></use></g><rect width="3517" height="60" x="1000" y="938.5"></rect></g></g><g data-mml-node="mrow" transform="translate(3178.7, -686)"><g data-mml-node="mn"><use xlink:xlink:href="#MJX-TEX-N-32"></use></g><g data-mml-node="mi" transform="translate(500, 0)"><use xlink:xlink:href="#MJX-TEX-I-61"></use></g></g><rect width="7146.4" height="60" x="120" y="220"></rect></g></g><g data-mml-node="mo" transform="translate(9292, 0)"><use xlink:xlink:href="#MJX-TEX-N-2E"></use></g></g></g></svg></mjx-container>
</div>
<svg style="display: none" id="MJX-SVG-global-cache"><defs><path id="MJX-TEX-I-61" d="M33 157Q33 258 109 349T280 441Q331 441 370 392Q386 422 416 422Q429 422 439 414T449 394Q449 381 412 234T374 68Q374 43 381 35T402 26Q411 27 422 35Q443 55 463 131Q469 151 473 152Q475 153 483 153H487Q506 153 506 144Q506 138 501 117T481 63T449 13Q436 0 417 -8Q409 -10 393 -10Q359 -10 336 5T306 36L300 51Q299 52 296 50Q294 48 292 46Q233 -10 172 -10Q117 -10 75 30T33 157ZM351 328Q351 334 346 350T323 385T277 405Q242 405 210 374T160 293Q131 214 119 129Q119 126 119 118T118 106Q118 61 136 44T179 26Q217 26 254 59T298 110Q300 114 325 217T351 328Z"></path><path id="MJX-TEX-I-78" d="M52 289Q59 331 106 386T222 442Q257 442 286 424T329 379Q371 442 430 442Q467 442 494 420T522 361Q522 332 508 314T481 292T458 288Q439 288 427 299T415 328Q415 374 465 391Q454 404 425 404Q412 404 406 402Q368 386 350 336Q290 115 290 78Q290 50 306 38T341 26Q378 26 414 59T463 140Q466 150 469 151T485 153H489Q504 153 504 145Q504 144 502 134Q486 77 440 33T333 -11Q263 -11 227 52Q186 -10 133 -10H127Q78 -10 57 16T35 71Q35 103 54 123T99 143Q142 143 142 101Q142 81 130 66T107 46T94 41L91 40Q91 39 97 36T113 29T132 26Q168 26 194 71Q203 87 217 139T245 247T261 313Q266 340 266 352Q266 380 251 392T217 404Q177 404 142 372T93 290Q91 281 88 280T72 278H58Q52 284 52 289Z"></path><path id="MJX-TEX-N-32" d="M109 429Q82 429 66 447T50 491Q50 562 103 614T235 666Q326 666 387 610T449 465Q449 422 429 383T381 315T301 241Q265 210 201 149L142 93L218 92Q375 92 385 97Q392 99 409 186V189H449V186Q448 183 436 95T421 3V0H50V19V31Q50 38 56 46T86 81Q115 113 136 137Q145 147 170 174T204 211T233 244T261 278T284 308T305 340T320 369T333 401T340 431T343 464Q343 527 309 573T212 619Q179 619 154 602T119 569T109 550Q109 549 114 549Q132 549 151 535T170 489Q170 464 154 447T109 429Z"></path><path id="MJX-TEX-N-2B" d="M56 237T56 250T70 270H369V420L370 570Q380 583 389 583Q402 583 409 568V270H707Q722 262 722 250T707 230H409V-68Q401 -82 391 -82H389H387Q375 -82 369 -68V230H70Q56 237 56 250Z"></path><path id="MJX-TEX-I-62" d="M73 647Q73 657 77 670T89 683Q90 683 161 688T234 694Q246 694 246 685T212 542Q204 508 195 472T180 418L176 399Q176 396 182 402Q231 442 283 442Q345 442 383 396T422 280Q422 169 343 79T173 -11Q123 -11 82 27T40 150V159Q40 180 48 217T97 414Q147 611 147 623T109 637Q104 637 101 637H96Q86 637 83 637T76 640T73 647ZM336 325V331Q336 405 275 405Q258 405 240 397T207 376T181 352T163 330L157 322L136 236Q114 150 114 114Q114 66 138 42Q154 26 178 26Q211 26 245 58Q270 81 285 114T318 219Q336 291 336 325Z"></path><path id="MJX-TEX-I-63" d="M34 159Q34 268 120 355T306 442Q362 442 394 418T427 355Q427 326 408 306T360 285Q341 285 330 295T319 325T330 359T352 380T366 386H367Q367 388 361 392T340 400T306 404Q276 404 249 390Q228 381 206 359Q162 315 142 235T121 119Q121 73 147 50Q169 26 205 26H209Q321 26 394 111Q403 121 406 121Q410 121 419 112T429 98T420 83T391 55T346 25T282 0T202 -11Q127 -11 81 37T34 159Z"></path><path id="MJX-TEX-N-3D" d="M56 347Q56 360 70 367H707Q722 359 722 347Q722 336 708 328L390 327H72Q56 332 56 347ZM56 153Q56 168 72 173H708Q722 163 722 153Q722 140 707 133H70Q56 140 56 153Z"></path><path id="MJX-TEX-N-30" d="M96 585Q152 666 249 666Q297 666 345 640T423 548Q460 465 460 320Q460 165 417 83Q397 41 362 16T301 -15T250 -22Q224 -22 198 -16T137 16T82 83Q39 165 39 320Q39 494 96 585ZM321 597Q291 629 250 629Q208 629 178 597Q153 571 145 525T137 333Q137 175 145 125T181 46Q209 16 250 16Q290 16 318 46Q347 76 354 130T362 333Q362 478 354 524T321 597Z"></path><path id="MJX-TEX-N-2212" d="M84 237T84 250T98 270H679Q694 262 694 250T679 230H98Q84 237 84 250Z"></path><path id="MJX-TEX-N-B1" d="M56 320T56 333T70 353H369V502Q369 651 371 655Q376 666 388 666Q402 666 405 654T409 596V500V353H707Q722 345 722 333Q722 320 707 313H409V40H707Q722 32 722 20T707 0H70Q56 7 56 20T70 40H369V313H70Q56 320 56 333Z"></path><path id="MJX-TEX-SO-221A" d="M263 249Q264 249 315 130T417 -108T470 -228L725 302Q981 837 982 839Q989 850 1001 850Q1008 850 1013 844T1020 832V826L741 243Q645 43 540 -176Q479 -303 469 -324T453 -348Q449 -350 436 -350L424 -349L315 -96Q206 156 205 156L171 130Q138 104 137 104L111 130L263 249Z"></path><path id="MJX-TEX-N-34" d="M462 0Q444 3 333 3Q217 3 199 0H190V46H221Q241 46 248 46T265 48T279 53T286 61Q287 63 287 115V165H28V211L179 442Q332 674 334 675Q336 677 355 677H373L379 671V211H471V165H379V114Q379 73 379 66T385 54Q393 47 442 46H471V0H462ZM293 211V545L74 212L183 211H293Z"></path><path id="MJX-TEX-N-2E" d="M78 60Q78 84 95 102T138 120Q162 120 180 104T199 61Q199 36 182 18T139 0T96 17T78 60Z"></path></defs></svg></body></html>
```

And this is the input html with some TeX formula:
```
<h1>Title</h1>

<div>
  When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
  $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$
</div>
```

**Comment by dpvc** [comment]
There is an issue with the xlink namespace being added twice, so you are ending up with `xlink:xlink:href` rather than the correct `xlink:href`.  Here is a modified version off your code that patches the problem for now.

```
const mathjax = require('mathjax-full/js/mathjax.js').mathjax;
const TeX = require('mathjax-full/js/input/tex.js').TeX;
const SVG = require('mathjax-full/js/output/svg.js').SVG;
const LiteAdaptor = require('mathjax-full/js/adaptors/liteAdaptor.js').LiteAdaptor;
const RegisterHTMLHandler = require('mathjax-full/js/handlers/html.js').RegisterHTMLHandler;
const AllPackages = require('mathjax-full/js/input/tex/AllPackages.js').AllPackages;

//
// Fix bug with xlink namespace being added twice
//
class myLiteAdaptor extends LiteAdaptor {
  setAttribute(node, name, value, ns) {
    if (ns) name = name.replace(/^.*:/, '');
    return super.setAttribute(node, name, value, ns);
  }
}

//
//  Read the HTML file
//
const htmlfile = require('fs').
    readFileSync("./tmp.html", 'utf8');

//
//  Create DOM adaptor and register it for HTML documents
//
const adaptor = new myLiteAdaptor({fontSize: 16});
RegisterHTMLHandler(adaptor);

//
//  Create input and output jax and a document using them on the content from the HTML file
//
const tex = new TeX({packages: AllPackages.sort().join(', ').split(/\s*,\s*/)});
const svg = new SVG({fontCache: 'global', exFactor: 8 / 16});
const html = mathjax.document(htmlfile, {InputJax: tex, OutputJax: svg});

//
//  Typeset the document
//
html.render();

//
//  Output the resulting HTML
//
console.log(adaptor.outerHTML(adaptor.root(html.document)));
```

**Comment by Aleyasen** [comment]
Thanks a lot @dpvc, your fix resolved the issue.
